export const GRAPH_ROPE_TEXT_WINDOW_CACHE_STATUS_UNCACHED = 'uncached-materialization';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_MISSING_HEAD = 'missing-head';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_MISSING_NODE = 'missing-node';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_MISSING_BLOB = 'missing-blob';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_INVALID_BYTE_RANGE = 'invalid-byte-range';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_INVALID_UTF8_BOUNDARY = 'invalid-utf8-boundary';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_INVALID_FACT = 'invalid-fact';

export type GraphRopeRuntimeObstructionCode =
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_MISSING_HEAD
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_MISSING_NODE
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_MISSING_BLOB
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_INVALID_BYTE_RANGE
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_INVALID_UTF8_BOUNDARY
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_INVALID_FACT;
