export const GRAPH_ROPE_TEXT_WINDOW_CACHE_STATUS_UNCACHED = 'uncached-materialization';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_MISSING_HEAD = 'missing-head';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_MISSING_NODE = 'missing-node';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_MISSING_BLOB = 'missing-blob';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_MISSING_CHECKPOINT = 'missing-checkpoint';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_INVALID_BYTE_RANGE = 'invalid-byte-range';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_INVALID_UTF8_BOUNDARY = 'invalid-utf8-boundary';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_INVALID_FACT = 'invalid-fact';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_CAUSAL_ANCHOR_UNAVAILABLE = 'causal-anchor-unavailable';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_CAUSAL_ANCHOR_ADMISSION_FAILED = 'causal-anchor-admission-failed';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_BASIS_NOT_ANCESTOR = 'basis-not-ancestor';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_MISSING_CAUSAL_EVIDENCE = 'missing-causal-evidence';
export const GRAPH_ROPE_RUNTIME_OBSTRUCTION_LINE_DIFF_LIMIT_EXCEEDED = 'line-diff-limit-exceeded';

export type GraphRopeRuntimeObstructionCode =
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_MISSING_HEAD
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_MISSING_NODE
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_MISSING_BLOB
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_MISSING_CHECKPOINT
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_INVALID_BYTE_RANGE
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_INVALID_UTF8_BOUNDARY
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_INVALID_FACT
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_CAUSAL_ANCHOR_UNAVAILABLE
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_CAUSAL_ANCHOR_ADMISSION_FAILED
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_BASIS_NOT_ANCESTOR
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_MISSING_CAUSAL_EVIDENCE
  | typeof GRAPH_ROPE_RUNTIME_OBSTRUCTION_LINE_DIFF_LIMIT_EXCEEDED;
