"""Reproduce the raw atom read/guard boundary through the public Edict CLI."""

import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import tempfile


def build(root, document, expected_kind=None, required_details=()):
    request = {
        "schema": "edict.compiler.settings/v1",
        "type": "compilerSettings",
        "operation": "build",
        document: f"edict.{document}.json",
    }
    result = subprocess.run(
        ["/edict/target/debug/edict"], cwd=root,
        input=json.dumps(request) + "\n", text=True, capture_output=True,
        timeout=120, check=False,
    )
    events = [json.loads(line) for stream in (result.stdout, result.stderr)
              for line in stream.splitlines()]
    diagnostics = [event for event in events if event.get("type") == "diagnostic"]
    statuses = [event for event in events if event.get("type") == "status"]
    expected_code = 0 if expected_kind is None else 2
    if (result.returncode != expected_code or len(statuses) != 1
            or statuses[0].get("exitCode") != expected_code):
        raise RuntimeError(f"Unexpected public build result: {result}")
    if expected_kind is None:
        if diagnostics:
            raise RuntimeError(f"Lawpack build produced diagnostics: {diagnostics}")
    elif (len(diagnostics) != 1 or diagnostics[0].get("kind") != expected_kind
          or any(detail not in diagnostics[0].get("message", "")
                 for detail in required_details)):
        raise RuntimeError(f"Unexpected refusal boundary: {diagnostics}")
    if document == "application":
        output = root / ".build/application"
        if output.exists() and any(output.rglob("*")):
            raise RuntimeError("Refused build published application artifacts")
    for event in events:
        print(json.dumps(event, sort_keys=True), flush=True)


def main():
    if not Path("/.dockerenv").is_file():
        raise RuntimeError("Run with the COPY-based node-atom-read Dockerfile")
    source = Path("/probe")
    definition = json.loads((source / "edict.lawpack.json").read_text())
    selection = definition["lawpack"]["targetAdapters"][0]["acceptedTargetIr"]
    schema = Path("/edict/docs/abi/edict-target-ir.cddl").read_bytes()
    if selection != {
        "id": "echo.span-ir/v2",
        "digest": "sha256:" + hashlib.sha256(schema).hexdigest(),
    }:
        raise RuntimeError("Probe does not select the pinned experimental IR contract")
    with tempfile.TemporaryDirectory(prefix="jedit-atom-read-") as scratch:
        root = Path(scratch)
        for document in ("edict.lawpack.json", "edict.application.json"):
            shutil.copyfile(source / document, root / document)
        shutil.copytree(source / "src", root / "src")
        build(root, "lawpack")
        digest = (root / "vendor/atom-read/manifest.sha256").read_text().strip()
        authored = (root / "src/ReplaceRange.edict").read_text()
        if authored.count(f'digest "{digest}"') != 1:
            raise RuntimeError("Authored lawpack import does not match generated bytes")
        provider = root / ".build/echo-provider"
        shutil.copytree("/echo-source/schemas/edict-provider/package/v1", provider)
        build(root, "application", "InvalidProviderInvocation",
              ("ArtifactSchemaMismatch", "06-target-ir"))
        shutil.rmtree(provider)
        shutil.copytree("/ordered-provider", provider)
        build(root, "application", "ProviderLowererRefused",
              ("UnsupportedSemantics", "core.echo-pure-operation"))
        if (root / "src/ReplaceRange.edict").read_text() != authored:
            raise RuntimeError("Witness changed the authored operation")
    print("JEDIT_NODE_ATOM_READ_PROVIDER_BOUNDARY_CONFIRMED", flush=True)


if __name__ == "__main__":
    main()
