export const WorkspaceCommandNames = Object.freeze({
  Edit: "edit",
  EditAlias: "e",
  Write: "write",
  WriteAlias: "w",
  Quit: "quit",
  QuitAlias: "q",
  QuitBang: "quit!",
  QuitBangAlias: "q!",
  WriteQuit: "wq",
  WriteQuitAlias: "x",
  TimeTravelDebugger: "ttd",
  Strand: "strand",
  Braid: "braid",
  Why: "why",
} as const);
